### ISSUE TITLE
Improved adaptive support

### ISSUE THREAD

**Issue by alexpattyn** [mpobaschnig/Vaults#10]
**Is your feature request related to a problem? Please describe.**
On smaller screens (e.g. pinephone and the librem 5) it would be easier to use the configuration dialogs if they took up the whole screen. 

**Describe the solution you'd like**
Windows should take up the full vertical space on small screens. 

**Additional context**
Possible resources: `libadwaita` and examples of adaptive menus in other projects like [clapper](https://github.com/Rafostar/clapper).

**Images**
Note: These were take on the mobile [QEMU image of PureOS](https://developer.puri.sm/Librem5/Development_Environment/Boards/qemu.html)

![image](https://user-images.githubusercontent.com/28536677/116595675-8eb8ea00-a8f1-11eb-8c4a-a21a513f511f.png)
![image](https://user-images.githubusercontent.com/28536677/116595737-9e383300-a8f1-11eb-88f2-b0b69f39107c.png)

**Comment by mpobaschnig** [comment]
Thanks for trying this in the VM.

I thought that dialogs might be good for mobile devices, since some other adaptive apps use this. I'll try to move away from dialogs with the next release.

**Comment by alexpattyn** [comment]
No problem! I'll check it out again on the next release. I know the clapper dev was waiting for a stable release of `libadwaita` before making improvements to various menus/dialogs. In the OP I've should've pointed to [lollypop](https://wiki.gnome.org/Apps/Lollypop) as an example for adaptive menus.
