### ISSUE TITLE
Implement system tray menu with list of vaults

### ISSUE THREAD

**Issue by piotrminkina** [mpobaschnig/vaults#113]
Thank you for the very good project that is Vaults. I think it surpasses even SiriKali in some respects. The way vaults are managed is somehow more user friendly.

Could you implement minimizing/closing the application to the system tray? It would be very cool if my vaults could be mounted directly from the menu, from the system tray. This would be especially useful with the auto-lock session option enabled. 

The way it would work is that when I click the Vaults icon in the system tray, a menu with a list of my vaults appears. When I click on the desired vault name, that vault is mounted. Of course, I then enter the password or it is automatically read from GNOME Keyring, etc.

**Comment by mpobaschnig** [comment]
Hi, thanks for the suggestion, but Vaults follows [GNOME HIG](https://developer.gnome.org/hig/principles.html) as best as possible which unfortunately does not include system trays. 

However, we could explore the possibility of implementing a [search provider](https://developer.gnome.org/documentation/tutorials/search-provider.html) for Vaults, where you can search your Vaults in the overview. When you select the Vault from the list that matches the query, it'd open either a password dialog if needed or immediately unlock if a password is set in the keyring when https://github.com/mpobaschnig/vaults/issues/89 is implemented.

I'll create an issue as follow up to track this idea.
