### ISSUE TITLE
The 'Add' button is grayed out

### ISSUE THREAD

**Issue by stepnjump** [mpobaschnig/Vaults#14]
**Steps to reproduce**

**Current behavior**

A clear and concise description of the current behavior.

**Expected behavior**

**Version information**

- Application:
- CryFS (if related):
- Gocryptfs (if related):
- Distribution:

**Additional information**

Please provide the terminal output when the bug happens and if applicable, add screenshots or screencasts to help explain your problem.
![129377434-56d870be-994f-4ad5-a513-f2c299a028fa](https://user-images.githubusercontent.com/8755316/130069330-08ed21aa-3b91-4744-92d9-5b5ba2c3c53e.png)

**Comment by mpobaschnig** [comment]
This is intentional, since vault name, password, confirmed password, encrypted data directory path and mount directory path is missing or not valid (as indicated beneath the names on the left side).

**Comment by stepnjump** [comment]
Yes I figured but EVEN if I populate the fields, it's not working anyway...
