### ISSUE TITLE
Improve app icon

### ISSUE THREAD

**Issue by jacsonah** [mpobaschnig/Vaults#15]
I have an improvement suggestion for the app icon.
What do you think about?
![vaults](https://user-images.githubusercontent.com/48760175/132959895-db5eb8a2-066c-41ae-8c0f-5fd187461056.png)

**Comment by mpobaschnig** [comment]
Hey, sorry for the late response and thanks for your suggestion!

I'm not quite sure about the symmetry and distance to borders of the inner part. When looking at Password Safe [icon](https://gitlab.gnome.org/World/PasswordSafe/-/blob/master/data/icons/hicolor/scalable/apps/org.gnome.PasswordSafe.svg), they use the same distance above and below. Maybe you could try the same distance as well?

Also, I think the shadow is a bit off? The shadow from the upper bars don't have the same direction as the lower ones. However, I'm not a designer, so I would welcome your opinion about this.

Could you also please attach a picture where you put your SVG into the [App Icon Preview](https://flathub.org/apps/details/org.gnome.design.AppIconPreview) app for reference with other apps, thanks!

**Comment by jacsonah** [comment]
Hi, I've been drafting some other icon models.
What do you think about this?
![io github mpobaschnig Vaults](https://user-images.githubusercontent.com/48760175/135700699-df50acf5-f5ad-4166-b390-615314ea5062.png)
![image](https://user-images.githubusercontent.com/48760175/135700707-c88fa94a-d854-4425-8c6e-00ceb4c3f2f3.png)

If you prefer I can fix the first icon too.

**Comment by mpobaschnig** [comment]
This looks very good! However, the first one fits the name "Vaults" much better in my opinion, as this one goes more into the "Safe" direction. So I think improving the first icon is a better idea.

**Comment by jacsonah** [comment]
I centralized the inner part and removed the shadows.
I'm not a designer either, so I don't have a technical suggestion of what could be improved.
![io github mpobaschnig Vaults](https://user-images.githubusercontent.com/48760175/136632412-fdbdb9bc-fb9e-4bd9-afe4-32ef42704dc4.png)
![image](https://user-images.githubusercontent.com/48760175/136632157-34bdd425-bc9c-4b4d-9905-ee7593e666b0.png)

**Comment by jacsonah** [comment]
Here it is with another color in the inner part.

![io github mpobaschnig Vaults](https://user-images.githubusercontent.com/48760175/136633526-19f0b09c-543d-4cf5-a60e-74874db5feac.png)

![image](https://user-images.githubusercontent.com/48760175/136633063-646893f3-da8a-4fbc-b400-52e6097d6ae6.png)

**Comment by jacsonah** [comment]
Merge request: #19

**Comment by mpobaschnig** [comment]
Closed with commit https://github.com/mpobaschnig/Vaults/commit/b7d19dc907259d0b2ccd892a749f79cc7ce1ed3d
