### ISSUE TITLE
Incorrect dialog size popup

### ISSUE THREAD

**Issue by Crono23** [mpobaschnig/Vaults#16]
**Steps to reproduce**

1. Open Vaults
2. Click on 'Add' 'Import' or 'Open'
3. See error

**Current behavior**

The dialog popup has incorrect size, thus not showing the content properly.

**Expected behavior**

The dialog popup has the right size, so there'd be no need to resize it manually.

**Version information**

- Application: Vaults
- CryFS (if related):
- Gocryptfs (if related):
- Distribution: Fedora Silverblue

**Additional information**

![Screenshot from 2021-09-27 18-27-46](https://user-images.githubusercontent.com/88884864/134901554-67d81b95-9a8c-4fa2-8201-5b56d09c6217.png)

**Comment by mpobaschnig** [comment]
Hey, thanks for the issue. This is already fixed in the redesign (#11) coming with the next release (hopefully soon).
