### ISSUE TITLE
Backend not detected when importing.

### ISSUE THREAD

**Issue by Crono23** [mpobaschnig/Vaults#24]
**Steps to reproduce**

1. Go to 'Import vault'
2. Select directory
3. Click next

**Current behavior**

Installed backend not detected when importing an already made vault. While creating and using new one works.

**Expected behavior**

Installed backend should be detected when importing vault.

**Version information**

- Application:0.2.0
- CryFS (if related):
- Gocryptfs (if related):
- Distribution:Fedora Silverblue

**Additional information**

[New vault](https://www.dropbox.com/s/x7qvpx5tibe2ufx/Screenshot%20from%202021-12-27%2002-37-04.png?dl=0) [Import vault](https://www.dropbox.com/s/i4og775lrasvj7w/Screenshot%20from%202021-12-27%2002-37-19.png?dl=0)

**Comment by mpobaschnig** [comment]
Is this only with gocryptfs or also with CryFS? Does the import work (since import button seems to be enabled), and if so, is the backend detected in the vault settings?

**Comment by Crono23** [comment]
Sorry I only tried with gocryptfs since that's what's available in Fedora repo, the gocryptfs version I have is 1.8.0.
The app closes when I tried pressing the import button, here's the terminal output :
"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui/import_vault_dialog.rs:542:66"

**Comment by mpobaschnig** [comment]
Thanks. I found the issue and will deploy a new version later today.
