### ISSUE TITLE
[X11] File picker window increases in size every time it is reopened

### ISSUE THREAD

**Issue by 3ship** [mpobaschnig/Vaults#28]
_Originally posted in https://github.com/mpobaschnig/Vaults/issues/25#issuecomment-1005625760_

On the Flatpak build 0.2.1, but it also happened in 0.1

As mentioned this happens whenever a file picker is opened. It doesn't seem to matter from which menu it was opened. Issue persists through restarts of the app.

**Comment by mpobaschnig** [comment]
Related:
https://gitlab.gnome.org/GNOME/gtk/-/issues/4723
https://gitlab.gnome.org/GNOME/gtk/-/issues/4136

So not a Vaults issue.
