### ISSUE TITLE
Better appdata summary?

### ISSUE THREAD

**Issue by bertob** [mpobaschnig/Vaults#33]
The current summary "An application for creating encrypted vaults for the GNOME desktop." isn't great (longer than 35 characters, not a call to action, too generic).

I'd suggest something like "Encrypt important files", or "Keep important files safe".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by mpobaschnig** [comment]
Thanks, the second suggestion sounds good to me!
