### ISSUE TITLE
Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

### ISSUE THREAD

**Issue by fastrizwaan** [mpobaschnig/Vaults#37]
When we go to **preferences** and **"Choose Encrypted Data Directory"** the console shows this:
```

(vaults:5): GVFS-WARNING **: 14:06:55.635: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

```

`flatpak run --filesystem=xdg-run/gvfsd  io.github.mpobaschnig.Vaults ` fixes the above error message

`--filesystem=xdg-run/gvfsd ` to manifest?

**Comment by mpobaschnig** [comment]
Also fixed in the flathub repository and will be used in the next release.
