### ISSUE TITLE
File chooser: Cannot select empty directory from inside

### ISSUE THREAD

**Issue by pymnh** [mpobaschnig/Vaults#38]
**Steps to reproduce**

1. Create new vault
2. Open file chooser to set either mount or data directory
3. Navigate into an existing empty folder you want to choose as directory

**Current behavior**

When in an empty directory in the file chooser, it is not possible to "select" the folder (button is greyed out). one needs to navigate one level up, mark the folder and can now click the select button

**Expected behavior**

When in an empty folder, it should be assumed that I could want to select the current directory as destination, and be offered to click the select button (or confirm via return-key)

**Version information**

- Application: 0.3.0 (flatpak)
- Distribution: Debian unstable

**Comment by teohhanhui** [comment]
This is a problem with the XDG Desktop Portal implementation, not a bug in this app. I've been experiencing the same problem while using Transmission.

**Comment by mpobaschnig** [comment]
Yes, this issue is GTK related.
