### ISSUE TITLE
No backends available

### ISSUE THREAD

**Issue by shdwchn10** [mpobaschnig/Vaults#41]
![Screenshot from 2022-05-10 20-58-49](https://user-images.githubusercontent.com/79763381/167692696-a5cd9be1-7cbd-416c-b1a6-615b14e23aa2.png)

Vaults can't find CryFS backend.

My setup: Fedora Silverblue 36, latest Vaults from Flathub stable, cryfs-0.11.2-1.fc36.

```
$ rpm -qi cryfs
Name        : cryfs
Version     : 0.11.2
Release     : 1.fc36
Architecture: x86_64
Install Date: Tue 10 May 2022 18:57:10 MSK
Group       : Unspecified
Size        : 4499524
License     : LGPLv3
Signature   : RSA/SHA256, Sun 27 Mar 2022 13:36:24 MSK, Key ID 999f7cbf38ab71f4
Source RPM  : cryfs-0.11.2-1.fc36.src.rpm
Build Date  : Sun 27 Mar 2022 13:05:17 MSK
Build Host  : buildvm-x86-27.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://www.cryfs.org/
Bug URL     : https://bugz.fedoraproject.org/cryfs
Summary     : Cryptographic filesystem for the cloud
Description :
CryFS provides a FUSE-based mount that encrypts file contents, file
sizes, metadata and directory structure. It uses encrypted same-size
blocks to store both the files themselves and the blocks' relations
to one another. These blocks are stored as individual files in the
base directory, which can then be synchronized to remote storage
(using an external tool)
```

**Comment by mpobaschnig** [comment]
Does cryfs actually work for you in terminal? What is the output of `cryfs -h`?

I'm getting this on my Fedora 36 Workstation machine:
```
cryfs: symbol lookup error: cryfs: undefined symbol: _ZN6spdlog5sinks15basic_file_sinkISt5mutexEC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb

```

So this is most likely related to Fedora having a broken package.

**Comment by shdwchn10** [comment]
:thinking: Yes I have the same problem with CryFS cli. I commented about this in RedHat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2041100#c6

**Comment by mpobaschnig** [comment]
No worries :)

Seems that the cryfs was compiled to wrong version of spdlog or updated later on, see https://github.com/cryfs/cryfs/issues/423 and https://bugs.archlinux.org/task/74438
