### ISSUE TITLE
"The encrypted data directory is not empty" error

### ISSUE THREAD

**Issue by andresmessina1701** [mpobaschnig/Vaults#42]
Situation:
My Linux partition was basically bricked a few days ago. All files intact, and I accessed them from new Linux partition, including vaults files.
- I placed the (gocryptfs) vault files into the correct place, all files intact. (home/*name*/.var/app/io.github.mpobaschnig.Vaults)
- Downloaded and installed gocryptfs back-end.
- I have the correct password to open the files.
- The "unlock" icon on Vaults lights up. I press it, enter my password, and the error "The encrypted data directory is not empty" appears.

I hope I came to ask at the right place. What does this error mean? and how to solve it?

**Comment by mpobaschnig** [comment]
How did you add your vaults? It basically means that when you add a new vault, the data directory (where the encrypted files are stored) should be empty.

Can you try removing the vault within Vaults, then importing it again?

**Comment by andresmessina1701** [comment]
I have now emptied the vault folders of all content, the same error, claiming it is not empty, persists.

**Comment by mpobaschnig** [comment]
How did you add it? Via + -> Import Vault?
