### ISSUE TITLE
Let us point the binary ourselve.

### ISSUE THREAD

**Issue by ghost** [mpobaschnig/vaults#58]
**Is your feature request related to a problem? Please describe.**
On fedora some backend don't work or aren't there.

**Describe the solution you'd like**
Let us in the settings tell the flatpak where the binary is.

**Additional context**
I know this might need to tweak permission but a warning when settings it manually (to change the settings of the flatpak would be welcomed).

**Comment by mpobaschnig** [comment]
The binaries need to be in $PATH to be found. I rather have https://github.com/mpobaschnig/vaults/pull/22, but for the time being I see some use cases where it might make sense.

Considering as part of https://github.com/mpobaschnig/vaults/issues/54.
