### ISSUE TITLE
Open/lock with commands

### ISSUE THREAD

**Issue by Acumane** [mpobaschnig/vaults#63]
I'm trying to make Vaults feel more integrated with my file manager. These two commands would make a world of difference:

`flatpak run io.github.mpobaschnig.Vaults open <vault>` would just launch the popup:
![p](https://github.com/mpobaschnig/vaults/assets/94324138/5e490e95-7c31-49b9-9df4-e8d10d5d496d)
Likewise, `flatpak run io.github.mpobaschnig.Vaults lock <vault>` does what you'd expect.

**Comment by mpobaschnig** [comment]
This is in the next release (0.7.0) which is published in the next few hours. You can use --open/-o and --close/-c <vault> to open/close the specific vault.
