### ISSUE TITLE
Backend is not detected

### ISSUE THREAD

**Issue by muhammad-ans** [mpobaschnig/vaults#70]
**Steps to reproduce**

I have put the gocryptfs binaries in ~.local/bin.
gocryptfs is not detected in vaults.

**Current behavior**
The Binaries are located in ~.local/bin.  They are not detected in the app but gocryptfs is accessible through terminal.
Here are screenshots.
![image](https://github.com/mpobaschnig/vaults/assets/77329029/ed589a5f-42fa-4f87-bf6b-f8547db87c66)
![image](https://github.com/mpobaschnig/vaults/assets/77329029/869d2684-10f4-4db8-8630-2f79ee9fe49e)

**Expected behavior**
Binaries should be detected as normal.

**Version information**
0.6.1

- Application: flatpak version 0.6.1
- Gocryptfs  version:   gocryptfs v2.4.0 without_openssl; go-fuse v2.3.0; 2023-06-10 go1.20.3 linux/amd64
- Distribution: Fedora silverblue 39 prerelease

**Comment by mpobaschnig** [comment]
Hi, can you try out following commands and report the output:
```
flatpak run --command=/bin/sh io.github.mpobaschnig.Vaults
flatpak-spawn --host gocryptfs --version
```

**Comment by muhammad-ans** [comment]
Here is the output:
![image](https://github.com/mpobaschnig/vaults/assets/77329029/df4699c2-44c4-46de-92ab-1159a1fec1d2)

**Comment by mpobaschnig** [comment]
Thanks. Has Vaults worked for you before, and if so, when did it start not working anymore? E.g. after updating, etc.

**Comment by muhammad-ans** [comment]
There are two things I did 
I updated the binaries
I changed location of binaries.
previously i put binaries in ~.bin and add it to the path in .bashrc.
One of them broke it.

**Comment by muhammad-ans** [comment]
Found the issue It had nothing to do with vaults app.
~.bash_profile file got deleted by me. Just restored it, Now it works.
Sorry for wasting your time.
