### ISSUE TITLE
Include encryption deps

### ISSUE THREAD

**Issue by alexpattyn** [mpobaschnig/vaults#8]
**Is your feature request related to a problem? Please describe.**
On distros like fedora silverblue you generally are discouraged from layering packages. 

**Describe the solution you'd like**
Include gocryptfs, CryFS, libfuse in the flatpak. 

**Additional context**
Considering these are sensitive deps I wouldn't want them included in the flatpak unless there was a way to have a flathub bot watch upstream for updates and make automatic PRs.

**Comment by mpobaschnig** [comment]
I tried this at the beginning, but was unsuccessful in doing so. According to [this](https://github.com/cryptomator/cryptomator/issues/729#issuecomment-781486200), [this](https://github.com/flathub/com.valvesoftware.Steam/issues/444#issuecomment-532531307) and [this](https://github.com/flathub/com.valvesoftware.Steam/issues/443#issuecomment-537119752) it is currently not possible to use fuse in a Flatpak. Maybe it is possible, but I'm not sure how.

**Comment by alexpattyn** [comment]
Gotcha! I figured there was some reason. However [borg does mount its archives as FUSE mounts](https://borgbackup.readthedocs.io/en/stable/usage/mount.html) and other flatpak apps like [pika](https://wiki.gnome.org/Apps/PikaBackup) and [vorta](https://vorta.borgbase.com/) don't require borg on the host. So those apps may offer a clue. I know [pika has a matrix room](https://matrix.to/#/#pika-backup:gnome.org?via=gnome.org&via=matrix.org&via=matrix.debian.social) if you wanted to talk to the dev.

**Comment by mpobaschnig** [comment]
Thanks, I'll look into it again.

**Comment by mpobaschnig** [comment]
This is now being implemented at https://github.com/mpobaschnig/Vaults/pull/22 but might take a while.

Help and contributions very much appreciated.

**Comment by mhogomchungu** [comment]
Greetings, 

 I have a project named [SiriKali](https://flathub.org/apps/io.github.mhogomchungu.sirikali) and it does what you are doing and i though i should assist in making vaults bundle its dependencies.

My project's manifest file is [here](https://github.com/flathub/io.github.mhogomchungu.sirikali/blob/4a6ae4822b58da9df363fc5651943792e0b70557/io.github.mhogomchungu.sirikali.json) and how to biuld and bundle Gocryptfs and Cryfs starts at line 218.

From within your flatpak application, you can get the "out of flatpak" path to where these binaries are installed by parsing the contents of "/.flatpak-info" and then get "Instance/app-path" option.

**Comment by mpobaschnig** [comment]
Thank you very much for your hints and help! I'll take a look at the weekend when I got some more time :)

**Comment by mpobaschnig** [comment]
Hey, I tried your approach and it worked, thanks a lot! I had hoped mounting gocryptfs directories without `flatpak-spawn --host` would work too but I guess this is probably too much to dive into. Maybe we'll switch over if someone finds out the exact problem.

**Comment by mhogomchungu** [comment]
FUSE is not permitted inside Flatpak by design so  using "flatpak-spawn --host" is the only available option.

**Comment by mpobaschnig** [comment]
Alright, then there's not much we can do here. Thanks!

**Comment by mhogomchungu** [comment]
The problem here was to bundle CryFs and Gocryptfs.

You can bundle them and then use ```flatpak-spawn --host``` to run them outside of flatpak. The outside path to these bundled binaries can be obtained using "flatpak-info" file i explained in my first post.

**Comment by mpobaschnig** [comment]
Yes, I tried all of it and it works great! However, I'm still wondering why cryfs works within flatpak while gocryptfs does not when they are both based on fuse.

**Comment by mhogomchungu** [comment]
Are you sure CryFs works within flatpak?

It does not work here and i am getting "fuse: device not found, try 'modprobe fuse' first" error.

**Comment by mpobaschnig** [comment]
Unless there's some magic happening, yes. I pushed some work to https://github.com/mpobaschnig/vaults/tree/update-dependencies if you want to look at it or try out (e.g. using GNOME Builder).

**Comment by Froggy232** [comment]
Hi,
Is this feature completed? If yes, do you know when it will land on flathub?
I really like this software, I think that the possibility to use it without adding (or layering on immutable distro) an additional package can be very important for flatpak package at least, maybe it would be a good idea to build a new release with this feature at least?
Thanks you a lot for your work, Vaults is a really great gnome app indeed.
Have a nice day, and thanks again!

**Comment by Froggy232** [comment]
Hi,
Thanks you a lot,  it's really a good news, I will wait then!
Thanks you again for your work, have a very nice day!
