### ISSUE TITLE
Validate remove action

### ISSUE THREAD

**Issue by yakushabb** [mpobaschnig/vaults#85]
**Steps to reproduce**

1. Create a new vault
2. Go to the vault setting
3. Click on the remove button

**Current behavior**

It removes the vault without any confirmation

**Expected behavior**

It should confirm the destructive operation.

**Version information**

- Application: 0.8.0-487e6c9
- CryFS (if related):
- Gocryptfs (if related):
- Distribution: Flatpak from Source code

**Additional information**

[vault.webm](https://github.com/mpobaschnig/vaults/assets/161761531/c05f1b74-704d-4cc5-9e38-528643cb9a42)

**Comment by mpobaschnig** [comment]
Hmm, might also be a good moment to port to AdwDialog which was recently introduced in libadwaita 1.5.
