### ISSUE TITLE
Mount check only compares directory names, not paths

### ISSUE THREAD

**Issue by Corax42** [mpobaschnig/vaults#95]
**Steps to reproduce**

1. Create a vault with a (non-hidden) mount directory called "Test"; do not unlock it.
2. Mount another filesystem in another (non-hidden) directory that is also called "Test".
3. Check that Vaults now shows the vault "Test" as unlocked.
4. Unmount the other filesystem.
5. Check that Vaults now shows the vault "Test" as locked.

**Current behavior**

The mount check in vault::Vault::is_mounted only compares the directory name of the vault's configured mount directory with the directory names of the mounts from VolumeMonitor. This easily results in false positives, as demostrated by the above steps.

In particular, when a vault is erroneously shown as unlocked, it is not possible to actually unlock it, since Vaults will only show a lock button. Clicking the lock button will result in the error message "An unknown error has occurred" (or something to that effect), since the vault is not in fact unlocked and mounted. This may or may not be related to https://github.com/mpobaschnig/vaults/issues/53#issuecomment-1978926615.

In my particular usecase, I store encrypted backup data on a USB disk that is mounted at "/run/media/${user}/Backup". This bug forces me to give the vault's mount directory a name other than "Backup"; otherwise as soon as the disk is mounted, Vaults will erroneously show the vault as unlocked, and cannot be used to actually unlock it.

**Expected behavior**

A vault will only be shown as unlocked if some filesystem has been mounted at the configured mount directory. Otherwise, the vault will be shown as locked. To accomplish this, the method vault::Vault::is_mounted should compare full, canonicalized directory paths instead of directory names only.

**Version information**

- Application: Vaults 0.9.0
- CryFS (if related): unrelated (not installed)
- Gocryptfs (if related): unrelated (version 2.4.0)
- Distribution: unrelated (Fedora Silverblue 40)

**Additional information**

I have a working fix and will open a PR in short order.

**Comment by Corax42** [comment]
It appears I cannot create branches or open PRs. I have instead attached a patch (as a .txt; GitHub did not accept a .patch).

Please review and advise.

[Issue_95_ Fix_mount_directory_identification.patch.txt](https://github.com/user-attachments/files/16900760/Issue_95_.Fix_mount_directory_identification.patch.txt)

**Comment by mpobaschnig** [comment]
Thanks for the patch! I'll look into it as soon as I get some more time.

**Comment by mpobaschnig** [comment]
Thanks for the bug report and the patch. Looks good to me! There are some other areas where we don't take the canonical path into account which I'll address in the next few days.
